/* Generated by mvllow/dots

    fontFamily
        SF Mono        | copied from system lib to user lib during setup
        SFMono-Regular | accessible by user (not as reliable, therefor only used as fallback)

    plugins
        hypercwd       | open new tabs in existing directory
*/

module.exports = {
  config: {
    fontFamily: "SF Mono, SFMono-Regular, Menlo, Consolas, Courier, monospace",
    fontSize: 12
  },
  plugins: ["hypercwd", "hyper-website-theme"]
};
