/* Generated by mvllow/dots

    fontFamily
        SF Mono        | Copied from system lib to user lib during setup
        SFMono-Regular | Accessible by user (not as reliable, therefor only used as fallback)
*/

module.exports = {
  config: {
    fontFamily: "SF Mono, SFMono-Regular, Menlo, Consolas, Courier, monospace",
    fontSize: 12,
    hyperTransparentVibrancy: {
      alpha: 0.7,
      vibrancy: "dark"
    }
  },
  plugins: ["hypercwd", "hyper-website-theme", "hyper-transparent-vibrancy"]
};
