/* Generated by mvllow/dots

    opacity            | set window transparency, provided by `hyper-opacity`
    fontFamily
        SF Mono        | copied from system lib to user lib during setup
        SFMono-Regular | accessible by user (less reliable fallback)
    fontSize           | todo?: detect preferred font size from existing source
    plugins
        hypercwd       | new tabs use current directory
        hyper-opacity  | enable window transparency
        nord-hyper     | nord theme
*/

module.exports = {
  config: {
    opacity: 0.92,
    fontFamily: "SF Mono, SFMono-Regular, Menlo, Consolas, Courier, monospace",
    fontSize: 12
  },
  plugins: ["hypercwd", "hyper-opacity", "nord-hyper"]
};
