" Generated by mvllow/dots

set packpath^=~/.vim
packadd minpac

call minpac#init()
call minpac#add('/usr/local/opt/fzf')
call minpac#add('junegunn/fzf.vim')

syntax off                             " Turn off syntax highlighting

set laststatus=0                       " Hide statusline
set splitbelow                         " Split vertical below
set splitright                         " Split horizontal right
set noswapfile                         " Do not create swap files
set viminfo=""                         " Do not create ~/.viminfo
set undofile                           " Enable persistent undo...
set undodir=~/.vim/undo                " ...and save state in ~/.vim/undo
set tabstop=2                          " Amount of indentation per tab byte
set shiftwidth=2                       " Same as tabstop but for indenting via `>>`
set expandtab                          " Prefer spaces over tabs
set autoindent                         " Auto indent new lines
set smartindent                        " Same as autoindent but for current syntax/style
set ignorecase                         " Case insensitive search...
set smartcase                          " ...unless using uppercase
set hidden                             " Allow unsaved hidden buffers

let mapleader=','                      " Sets the <leader> character
let $FZF_DEFAULT_COMMAND = 'ag -g ""'  " Fuzzy search via `ag`

inoremap jk <esc>                      " Exit insert mode
nnoremap K 5k                          " Move up by 5 lines
nnoremap J 5j                          " Move down by 5 lines
nnoremap k gk                          " Natural movement up through wrapped lines
nnoremap j gj                          " Natural movement down through wrapped lines
nnoremap <silent> <leader>s :bnext<cr> " Focus next buffer
nnoremap <silent> <leader>a :bprev<cr> " Focus prev buffer
nnoremap <silent> <leader>d :bd<cr>    " Close current buffer
nnoremap <leader>f :FZF<cr>            " Open FZF menu

command! PackUpdate packadd minpac | source $MYVIMRC | call minpac#update('', {'do': 'call minpac#status()'})
command! PackClean  packadd minpac | source $MYVIMRC | call minpac#clean()
command! PackStatus packadd minpac | source $MYVIMRC | call minpac#status()
