" Generated by mvllow/dots

set packpath^=~/.vim
packadd minpac

call minpac#init()
call minpac#add('arcticicestudio/nord-vim')
call minpac#add('burner/vim-svelte')
call minpac#add('fatih/vim-go')
call minpac#add('itchyny/lightline.vim')
call minpac#add('junegunn/fzf', { 'do': './install --all' })
call minpac#add('junegunn/fzf.vim')
call minpac#add('mxw/vim-jsx')
call minpac#add('pangloss/vim-javascript')
call minpac#add('sheerun/vim-polyglot')
call minpac#add('w0rp/ale')

let mapleader=','

" ALE
"
" lint and fix javascript/svelte/prettier-supported langs
"
let g:ale_fix_on_save = 1
let g:ale_fixers = { 'javascript': ['eslint', 'prettier'], 'svelte': ['eslint', 'prettier'] }
let g:ale_lint_on_enter = 0
let g:ale_lint_on_save = 1
let g:ale_linter_aliases = {'svelte': ['css', 'javascript']}
let g:ale_linters = { 'javascript': ['eslint', 'prettier'], 'svelte': ['eslint', 'prettier'] }
let g:ale_sign_error = '✖'

" Golang
"
" disable conflicting `K` keybind
"
let g:go_doc_keywordprg_enabled = 0

" Appearance
" 
" attemps to set transparent sign column, fallback to black
"
syntax on
set noshowmode
set laststatus=2
set signcolumn=yes
hi SignColumn ctermbg=black
hi SignColumn ctermbg=NONE
let g:lightline = { 'colorscheme': 'nord' }
colorscheme nord

" Splits
"
" splitbelow | default vertical split to below (vs above)
" splitright | default horizontal split to right (vs left)
set splitbelow
set splitright

" Vim files
"
" noswapfile | do not create swap files
" viminfo    | do not create ~/.viminfo
" undofile   | enable persistent undo...
" undodir    | ...and save states in ~/.vim/undo
"
set noswapfile
set viminfo=""
set undofile
set undodir=~/.vim/undo

" Tabs and spacing
"
" tabstop     | amount of indentation per tab byte 
" shiftwidth  | same as tabstop except when manually indenting via `>>`
" expandtab   | prefer spaces over tabs
" autoindent  | auto indent on new lines or where otherwise appropriate
" smartindent | same as autoindent except reacts to current syntax/style
"
set tabstop=2
set shiftwidth=2
set expandtab
set autoindent
set smartindent

" Search
"
" ignorecase       | case insensitive search...
" smartcase        | ...unless using uppercase
"
" <leader>f -> FZF | open FZF menu
set ignorecase
set smartcase

let $FZF_DEFAULT_COMMAND = 'ag -g ""'
nnoremap <leader>f :FZF<cr>

" Movements
"
" jk -> esc        | exit insert mode
" J -> 5j, K -> 5k | move up or down by 5 lines
" j -> gj, k -> gk | natural vertical movement through wrapped lines
"
inoremap jk <esc>
nnoremap J 5j
nnoremap K 5k
nnoremap j gj
nnoremap k gk

" Buffer manipulation
" 
" hidden               | allow unsaved hidden buffers
" <leader>s -> bnext   | focus next buffer
" <leader>a -> bprev   | focus previous buffer
" <leader>d -> bdelete | close current buffer
"
set hidden
nnoremap <silent> <leader>s :bnext<cr>
nnoremap <silent> <leader>a :bprev<cr>
nnoremap <silent> <leader>d :bd<cr>

" Minpac plugin manager
"
" PackUpdate | install and update plugins
" PackClean  | remove unused plugins
" PackStatus | show plugin status
"
command! PackUpdate packadd minpac | source $MYVIMRC | call minpac#update('', {'do': 'call minpac#status()'})
command! PackClean  packadd minpac | source $MYVIMRC | call minpac#clean()
command! PackStatus packadd minpac | source $MYVIMRC | call minpac#status()
