# Generated by mvllow/dots

if [ gpg ]; then
	export GPG_TTY=$(tty)
fi

if [ nvim ]; then
	alias vi='nvim'
fi

if [ code-insiders ] && ! [ code ]; then
	alias code='code-insiders'
fi

if [ git ]; then
	alias chop='git branch --merged | egrep -v "(^\*|master)" | xargs git branch -d'
fi

if [ -d /usr/local/lib/node_modules/pure-prompt ]; then
	autoload -U promptinit; promptinit
	prompt pure
fi

if [ -f ~/.config/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]; then
	source ~/.config/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
fi
