foreground               #f7f7f7
background               #1a1a1a
selection_foreground     #f7f7f7
selection_background     #262626

cursor                   #f7f7f7
cursor_text_color        #1a1a1a

url_color                #737373

active_tab_foreground    #f7f7f7
active_tab_background    #262626
inactive_tab_foreground  #737373
inactive_tab_background  #1a1a1a

# black
color0   #333333
color8   #737373

# red
color1   #c75c6a
color9   #c75c6a

# green
color2   #97be45
color10  #97be45

# yellow
color3   #c75c6a
color11  #c75c6a

# blue
color4   #a3a3a3
color12  #a3a3a3

# magenta
color5   #9745be
color13  #9745be

# cyan
color6   #78ccc5
color14  #78ccc5

# white
color7   #f7f7f7
color15  #f7f7f7

