foreground               #131313
background               #fefefe
selection_foreground     #131313
selection_background     #f5f5f5

cursor                   #131313
cursor_text_color        #fefefe

url_color                #636363

active_tab_foreground    #131313
active_tab_background    #f5f5f5
inactive_tab_foreground  #949494
inactive_tab_background  #fefefe

# black
color0   #e8e8e8
color8   #949494

# red
color1   #c75c6a
color9   #c75c6a

# green
color2   #97be45
color10  #97be45

# yellow
color3   #c75c6a
color11  #c75c6a

# blue
color4   #636363
color12  #636363

# magenta
color5   #9745be
color13  #9745be

# cyan
color6   #78ccc5
color14  #78ccc5

# white
color7   #131313
color15  #131313

