# tmux macOS keymaps
# Inspired by https://www.joshmedeski.com/posts/macos-keyboard-shortcuts-for-tmux
#
# Find hex value for key combination via `xxd -psd`
# '\x02' is the escaped equivalent of control+b, or the default tmux prefix

# Select windows 0 to 9.
map cmd+1 send_text all \x021
map cmd+2 send_text all \x022
map cmd+3 send_text all \x023
map cmd+4 send_text all \x024
map cmd+5 send_text all \x025
map cmd+6 send_text all \x026
map cmd+7 send_text all \x027
map cmd+8 send_text all \x028
map cmd+9 send_text all \x029

# Break the current pane out of the window.
map cmd+shift+t send_text all \x02!
# Rename the current window.
map cmd+, send_text all \x02,
# Switch the attached client back to the last session.
map cmd+shift+l send_text all \x02L
# Create a new window.
map cmd+t send_text all \x02c
# Detach the current client.
map cmd+d send_text all \x02d
# Change to the next window.
map cmd+shift+] send_text all \x02n
# Change to the previous window.
map cmd+shift+[ send_text all \x02p
# Select a new session for the attached client interactively.
map cmd+k send_text all \x02s
# Kill the current pane.
map cmd+w send_text all \x02x
# Toggle zoom state of the current pane.
map cmd+f send_text all \x02z

# Open 'lazygit'.
map cmd+g send_text all \x02g
