map cmd+f       toggle_layout stack
map cmd+,       set_tab_title
map cmd+t       new_tab_with_cwd
map cmd+enter   new_window_with_cwd
map cmd+[       previous_window
map cmd+]       next_window
map cmd+u       kitten unicode_input
map cmd+d       detach_window new-tab
map cmd+shift+d detach_window ask
map cmd+w       close_window
map cmd+q       quit
map cmd+up      move_window up
map cmd+left    move_window left
map cmd+right   move_window right
map cmd+down    move_window down
