# Theme, either `rose-pine.conf` or `nord.conf`
include nord.conf

editor '/opt/homebrew/bin/nvim'

# Window
window_border_width 0
window_padding_width 10

# Titlebar
macos_titlebar_color background
hide_window_decorations titlebar-only

# Tabs
bell_on_tab no
tab_bar_edge top
tab_bar_margin_width 10
tab_bar_style separator
tab_separator '   |   '

# Font
adjust_line_height 110%
font_family Cartograph CF
font_size 13

# Cursor
cursor_blink_interval 0
