include themes/rose-pine.conf

adjust_line_height 160%
font_family IBM Plex Mono
font_size 14

bell_on_tab no
cursor_blink_interval 0
editor '/opt/homebrew/bin/nvim'
enable_audio_bell no
enabled_layouts tall
hide_window_decorations titlebar-only
background_opacity 0.989

## Hide mouse after typing
## Negative value hides immediately, 0 disables hiding
mouse_hide_wait -1

shell_integration no-cursor
cursor_shape block

allow_remote_control yes

tab_bar_style separator
tab_separator '  |  '
window_border_width 0
window_padding_width 10

map cmd+[ previous_window
map cmd+] next_window
map cmd+t new_tab_with_cwd
map cmd+enter new_window_with_cwd
map cmd+w close_window
map cmd+up move_window up
map cmd+left move_window left
map cmd+right move_window right
map cmd+down move_window down
