include themes/rose-pine

allow_remote_control yes

enable_audio_bell no

adjust_line_height 150%
font_family SF Mono
font_size 13.5

cursor_blink_interval 0
cursor_shape block
mouse_hide_wait -1

# Set background_opacity to minimum of 0.989 to hide macOS window border
background_opacity 0.989

hide_window_decorations titlebar-only
window_padding_width 10

active_tab_font_style normal
tab_bar_style separator
tab_title_template " {fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{title} "
tab_separator ""

map cmd+enter new_window_with_cwd
map cmd+w close_window
map cmd+up move_window up
map cmd+down move_window down
map cmd+left move_window left
map cmd+right move_window right
map cmd+] next_window
map cmd+[ previous_window
map cmd+t new_tab_with_cwd
map cmd+d detach_tab ask
