unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

set -g escape-time 0          # zero-out escape time delay
set -g base-index 1           # start indexing windows at 1 instead of 0
set -g detach-on-destroy off  # don't exit from tmux when closing a session 
set -g history-limit 1000000  # significantly increase history size
set -g mouse on               # enable mouse support
set -g renumber-windows on    # renumber all windows when any window is closed

set -g status-interval 2      # update status every 2 seconds
set -g status-left-length 200 # increase status line length
set -g status-position top    # macOS / darwin style
set -g status-right ''        # empty
set -g status-left                  ' #[bg=green]#S'

set -g pane-active-border-style     'fg=magenta,bg=default'
set -g pane-border-style            'fg=brightblack,bg=default'

set-option -g default-terminal        'screen-256color'
set-option -g terminal-overrides      ',xterm-256color:RGB'

bind '%' split-window -c '#{pane_current_path}' -h
bind '"' split-window -c '#{pane_current_path}'
bind c   new-window   -c '#{pane_current_path}'
bind h   select-pane  -L
bind j   select-pane  -D
bind k   select-pane  -U
bind l   select-pane  -R

bind-key -n C-g new-window -n 'git' lazygit

bind-key x kill-pane # skip "kill-pane 1? (y/n)" prompt (cmd+w)
