start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 30

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Possible values: (qwerty|dvorak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
[key-mapping]
	preset = 'qwerty'

[gaps]
	inner.horizontal = 15
	inner.vertical   = 15
	outer.left       = 15
	outer.bottom     = 15
	outer.top        = 15
	outer.right      = 15

[mode.main.binding]
	alt-enter = 'exec-and-forget open -a /Applications/Ghostty.app'

	# See: https://nikitabobko.github.io/AeroSpace/commands#layout
	alt-slash = 'layout tiles horizontal vertical'
	alt-comma = 'layout accordion horizontal vertical'

	alt-f = 'fullscreen'

	alt-h = 'focus left'
	alt-j = 'focus down'
	alt-k = 'focus up'
	alt-l = 'focus right'

	alt-shift-h = 'move left'
	alt-shift-j = 'move down'
	alt-shift-k = 'move up'
	alt-shift-l = 'move right'

	alt-shift-left  = 'join-with left'
	alt-shift-down  = 'join-with down'
	alt-shift-up    = 'join-with up'
	alt-shift-right = 'join-with right'

	alt-1 = 'workspace 1'
	alt-2 = 'workspace 2'
	alt-3 = 'workspace 3'
	alt-4 = 'workspace 4'
	alt-5 = 'workspace 5'
	alt-6 = 'workspace 6'
	alt-7 = 'workspace 7'
	alt-8 = 'workspace 8'
	alt-9 = 'workspace 9'

	alt-shift-1 = 'move-node-to-workspace 1'
	alt-shift-2 = 'move-node-to-workspace 2'
	alt-shift-3 = 'move-node-to-workspace 3'
	alt-shift-4 = 'move-node-to-workspace 4'
	alt-shift-5 = 'move-node-to-workspace 5'
	alt-shift-6 = 'move-node-to-workspace 6'
	alt-shift-7 = 'move-node-to-workspace 7'
	alt-shift-8 = 'move-node-to-workspace 8'
	alt-shift-9 = 'move-node-to-workspace 9'

	alt-b = 'flatten-workspace-tree' # reset layout
	alt-g = 'layout floating tiling'

	alt-shift-semicolon = 'reload-config'

[[on-window-detected]]
	if.app-name-regex-substring = 'Ghostty'
	run = 'move-node-to-workspace 1'

[[on-window-detected]]
	if.app-name-regex-substring = 'Google Chrome'
	run = 'move-node-to-workspace 2'

[[on-window-detected]]
	if.app-name-regex-substring = 'Microsoft Teams'
	run = 'move-node-to-workspace 6'
