gui:
  authorColors:
    "*": magenta
  skipRewordInEditorWarning: true
  theme:
    selectedLineBgColor:
      - black
    selectedRangeBgColor:
      - reverse
keybinding:
  files:
    viewResetOptions: null
