gui:
  authorColors:
    "*": magenta
  showBottomLine: false
  showCommandLog: false
  showListFooter: false
  theme:
    selectedLineBgColor:
      - default
    selectedRangeBgColor:
      - reverse
