SHELL := /bin/sh

install:
	@echo Installing neovim, language servers, and formatters
	sh ./util/install.sh

uninstall:
	@echo Removing neovim, language servers, and formatters
	sh ./util/uninstall.sh
